from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path


@dataclass(frozen=True, slots=True)
class SfzRegion:
    sample: str
    root_key: int
    low_key: int = 0
    high_key: int = 127
    low_velocity: int = 1
    high_velocity: int = 127
    release: float = 0.12
    loop_start: int | None = None
    loop_end: int | None = None
    loop_crossfade: float | None = None

    def validate(self) -> None:
        for name, value in {
            "root_key": self.root_key,
            "low_key": self.low_key,
            "high_key": self.high_key,
            "low_velocity": self.low_velocity,
            "high_velocity": self.high_velocity,
        }.items():
            if not 0 <= value <= 127:
                raise ValueError(f"{name} must be between 0 and 127")
        if self.low_key > self.high_key:
            raise ValueError("low_key must not exceed high_key")
        if self.low_velocity > self.high_velocity:
            raise ValueError("low_velocity must not exceed high_velocity")
        if self.release < 0:
            raise ValueError("release must be non-negative")
        if (self.loop_start is None) != (self.loop_end is None):
            raise ValueError("loop_start and loop_end must be specified together")
        if self.loop_start is not None and self.loop_end is not None:
            if self.loop_start < 0 or self.loop_end <= self.loop_start:
                raise ValueError("loop points must define a positive range")
        if self.loop_crossfade is not None and self.loop_crossfade < 0:
            raise ValueError("loop_crossfade must be non-negative")


def render_sfz(regions: list[SfzRegion]) -> str:
    if not regions:
        raise ValueError("at least one region is required")
    lines = ["// Generated by audio2instrument", "<control>", "default_path=Samples/", ""]
    for region in regions:
        region.validate()
        sample_name = Path(region.sample).as_posix()
        lines.extend(
            [
                "<region>",
                f"sample={sample_name}",
                f"pitch_keycenter={region.root_key}",
                f"lokey={region.low_key}",
                f"hikey={region.high_key}",
                f"lovel={region.low_velocity}",
                f"hivel={region.high_velocity}",
                f"ampeg_release={region.release:.6f}",
            ]
        )
        if region.loop_start is not None and region.loop_end is not None:
            lines.extend(
                [
                    "loop_mode=loop_sustain",
                    f"loop_start={region.loop_start}",
                    # SFZ loop_end is inclusive; internal ranges use Python's exclusive end.
                    f"loop_end={region.loop_end - 1}",
                ]
            )
            if region.loop_crossfade is not None:
                lines.append(f"loop_crossfade={region.loop_crossfade:.6f}")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"
